# Generated by Django 5.1.15 on 2026-08-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_taskauditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="resolution_notes",
            field=models.TextField(blank=True),
        ),
    ]
