# Generated by Django 5.1.15 on 2026-09-23 15:04

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_project_latitude_project_longitude"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "base_manager_name": "all_objects",
                "ordering": ["order", "estimated_start"],
            },
        ),
        migrations.AlterModelManagers(
            name="task",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="expense",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("received", "Received"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="received",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="currency",
            field=models.CharField(
                choices=[("EUR", "EUR"), ("MKD", "MKD")], default="EUR", max_length=3
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="document",
            field=models.ForeignKey(
                blank=True,
                help_text="The invoice PDF.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenses",
                to="core.document",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="invoice_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="expense",
            name="original_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=16, null=True
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="vat_rate",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("18.00"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="building_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="project",
            name="investor",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="task",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="is_milestone",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                help_text="Main contractor on this position (shown on the Gantt).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="core.vendor",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="wbs_code",
            field=models.CharField(
                blank=True, help_text="Position code, e.g. А01 or А01.1", max_length=30
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="estimated_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="estimated_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="progress_pct",
            field=models.PositiveIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
