# Generated by Django 5.1.15 on 2026-09-23 15:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

# North Macedonia public holidays (non-working for all citizens), incl. substitute Mondays
# when a holiday falls on a Sunday. Sources: officeholidays.com, qppstudio.net (checked 23.09.2026).
# They apply to every project; per-project days are added in Settings -> Calendar.
MK_HOLIDAYS = [
    ("2026-01-01", "Нова година"), ("2026-01-07", "Божиќ (православен)"), ("2026-03-20", "Рамазан Бајрам"),
    ("2026-04-13", "Велигденски понеделник"), ("2026-05-01", "Ден на трудот"),
    ("2026-05-25", "Св. Кирил и Методиј (заменски)"), ("2026-08-03", "Илинден (заменски)"),
    ("2026-09-08", "Ден на независноста"), ("2026-10-12", "Ден на востанието (заменски)"),
    ("2026-10-23", "Ден на македонската револуционерна борба"), ("2026-12-08", "Св. Климент Охридски"),
    ("2027-01-01", "Нова година"), ("2027-01-07", "Божиќ (православен)"), ("2027-03-09", "Рамазан Бајрам"),
    ("2027-05-01", "Ден на трудот"), ("2027-05-03", "Велигденски понеделник"),
    ("2027-05-24", "Св. Кирил и Методиј"), ("2027-08-02", "Илинден"), ("2027-09-08", "Ден на независноста"),
    ("2027-10-11", "Ден на востанието"), ("2027-10-23", "Ден на македонската револуционерна борба"),
    ("2027-12-08", "Св. Климент Охридски"),
]


def copy_predecessors(apps, schema_editor):
    Task = apps.get_model("core", "Task")
    Dep = apps.get_model("core", "TaskDependency")
    Through = Task.predecessors.through
    for row in Through.objects.all():
        if row.from_task_id != row.to_task_id:
            Dep.objects.get_or_create(predecessor_id=row.to_task_id, successor_id=row.from_task_id,
                                      defaults={"type": "FS", "lag_days": 0})


def seed_holidays(apps, schema_editor):
    import datetime
    Exc = apps.get_model("core", "CalendarException")
    for d, name in MK_HOLIDAYS:
        Exc.objects.get_or_create(project=None, date=datetime.date.fromisoformat(d), defaults={"name": name})


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_phase0_wbs_invoice_softdelete"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="calendar_mode",
            field=models.CharField(
                choices=[
                    ("project", "Project calendar"),
                    ("seven_day", "7-day (calendar days)"),
                ],
                default="project",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="constraint_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="constraint_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "As soon as possible"),
                    ("snet", "Start no earlier than"),
                    ("fnlt", "Finish no later than"),
                    ("mso", "Must start on"),
                ],
                default="",
                max_length=4,
            ),
        ),
        migrations.CreateModel(
            name="Baseline",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="baselines",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BaselineTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateField(blank=True, null=True)),
                ("end", models.DateField(blank=True, null=True)),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "baseline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.baseline",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="baseline_items",
                        to="core.task",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("working_weekdays", models.JSONField(default=list)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar",
                        to="core.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CalendarException",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("name", models.CharField(max_length=120)),
                (
                    "is_working",
                    models.BooleanField(
                        default=False,
                        help_text="True = extra working day (e.g. a Sunday pour).",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_exceptions",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "unique_together": {("project", "date")},
            },
        ),
        migrations.CreateModel(
            name="TaskDependency",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("FS", "Finish-to-start"),
                            ("SS", "Start-to-start"),
                            ("FF", "Finish-to-finish"),
                            ("SF", "Start-to-finish"),
                        ],
                        default="FS",
                        max_length=2,
                    ),
                ),
                ("lag_days", models.IntegerField(default=0)),
                (
                    "predecessor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="successor_links",
                        to="core.task",
                    ),
                ),
                (
                    "successor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predecessor_links",
                        to="core.task",
                    ),
                ),
            ],
            options={
                "unique_together": {("predecessor", "successor")},
            },
        ),
        migrations.RunPython(copy_predecessors, migrations.RunPython.noop),
        migrations.RunPython(seed_holidays, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="task",
            name="predecessors",
        ),
    ]
