// UI text: key -> [Македонски, English]. Placeholders in {braces}.
const S = {
  // common
  'common.add': ['Додај', 'Add'],
  'common.back': ['Назад', 'Back'],
  'common.cancel': ['Откажи', 'Cancel'],
  'common.close': ['Затвори', 'Close'],
  'common.confirm': ['Потврди', 'Confirm'],
  'common.delete': ['Избриши', 'Delete'],
  'common.loading': ['Се вчитува…', 'Loading…'],
  'common.noProject': ['Нема избран проект', 'No project selected'],
  'common.noProjectHint': ['Изберете проект од левата страна или креирајте нов.', 'Pick a project on the left, or create a new one.'],
  'common.remove': ['Отстрани', 'Remove'],
  'common.save': ['Зачувај', 'Save'],
  'common.saving': ['Се зачувува…', 'Saving…'],
  'common.undo': ['Врати', 'Undo'],

  // navigation / top bar
  'nav.analytics': ['Анализа', 'Analytics'],
  'nav.budget': ['Буџет и фактури', 'Budget & invoices'],
  'nav.collapse': ['Собери мени', 'Collapse menu'],
  'nav.expand': ['Прошири мени', 'Expand menu'],
  'nav.import': ['Увоз од Excel', 'Import from Excel'],
  'nav.main': ['Главна навигација', 'Main navigation'],
  'nav.newProject': ['Нов проект', 'New project'],
  'nav.noProjects': ['Сè уште нема проекти', 'No projects yet'],
  'nav.operations': ['Операции (CRM)', 'Operations (CRM)'],
  'nav.overview': ['Преглед', 'Overview'],
  'nav.portfolio': ['Портфолио', 'Portfolio'],
  'nav.project': ['Проект', 'Project'],
  'nav.schedule': ['Распоред', 'Schedule'],
  'nav.selectProject': ['Изберете проект', 'Select a project'],
  'nav.settings': ['Поставки', 'Settings'],
  'nav.taskReport': ['Извештај', 'Report'],
  'nav.thisProject': ['Овој проект', 'This project'],
  'nav.tools': ['Алатки', 'Tools'],
  'top.account': ['Корисник', 'Account'],
  'top.currency': ['Валута на приказ', 'Display currency'],
  'top.language': ['Јазик', 'Language'],
  'top.signOut': ['Одјави се', 'Sign out'],

  // login
  'login.failed': ['Најавата не успеа. Обидете се повторно.', 'Sign-in failed. Please try again.'],
  'login.invalid': ['Погрешно корисничко име или лозинка.', 'Wrong username or password.'],
  'login.note': ['Користете ја сметката што ви ја отвори администраторот.', 'Use the account your administrator created for you.'],
  'login.password': ['Лозинка', 'Password'],
  'login.signIn': ['Најави се', 'Sign in'],
  'login.signingIn': ['Се најавува…', 'Signing in…'],
  'login.tagline': ['Распоред, буџет и фактури на секој објект — на едно место.', 'Schedule, budget and invoices for every site — in one place.'],
  'login.taglineSub': ['Управување со градежни проекти за United Build Group.', 'Construction project management for United Build Group.'],
  'login.title': ['Најава', 'Sign in'],
  'login.username': ['Корисничко име', 'Username'],

  // portfolio
  'portfolio.budget': ['Буџет', 'Budget'],
  'portfolio.completion': ['Изведено', 'Completion'],
  'portfolio.currentlyOn': ['Моментално', 'Currently on'],
  'portfolio.empty': ['Сè уште нема проекти', 'No projects yet'],
  'portfolio.emptyHint': ['Креирајте проект во апликацијата или увезете го од Excel.', 'Create a project in the app, or import one from Excel.'],
  'portfolio.invoiced': ['Фактурирано', 'Invoiced'],
  'portfolio.map': ['Локации', 'Locations'],
  'portfolio.mapStyle': ['Приказ на мапа', 'Map style'],
  'portfolio.noAddress': ['Нема адреса', 'No address'],
  'portfolio.noCoords': ['Ниеден проект нема координати — внесете ги во Поставки.', 'No project has coordinates yet — add them in Settings.'],
  'portfolio.noRenders': ['Нема прикачени рендери.', 'No renders attached yet.'],
  'portfolio.open': ['Отвори проект', 'Open project'],
  'portfolio.plannedEnd': ['Планиран крај', 'Planned end'],
  'portfolio.renders': ['Рендери и планови', 'Renders & plans'],
  'portfolio.satellite': ['Сателит', 'Satellite'],
  'portfolio.start': ['Почеток', 'Start'],
  'portfolio.street': ['Мапа', 'Map'],
  'portfolio.subtitle': ['{n} проекти', '{n} projects'],
  'portfolio.timeElapsed': ['Изминато {n} % од планираното време', '{n} % of planned time elapsed'],
  'portfolio.title': ['Портфолио', 'Portfolio'],
  'projectStatus.planning': ['Планирање', 'Planning'],
  'projectStatus.active': ['Активен', 'Active'],
  'projectStatus.on_hold': ['Паузиран', 'On hold'],
  'projectStatus.completed': ['Завршен', 'Completed'],

  // project overview
  'overview.aheadItem': ['{n} позиции се фактурирани без пријавен напредок', '{n} positions invoiced with no reported progress'],
  'overview.allGood': ['Ништо не бара внимание.', 'Nothing needs attention.'],
  'overview.attention': ['Бара внимание', 'Needs attention'],
  'overview.barsHint': ['Проверка за префактурирање', 'Over-billing check'],
  'overview.barsTitle': ['Изведено наспроти фактурирано наспроти време', 'Work done vs. invoiced vs. time'],
  'overview.budget': ['Буџет', 'Budget'],
  'overview.byGroup': ['Буџет по групи', 'Budget by group'],
  'overview.emptyHint': ['Додадете позиции во Распоред или увезете ги од Excel.', 'Add positions in Schedule, or import them from Excel.'],
  'overview.emptyTitle': ['Проектот сè уште нема позиции', 'This project has no positions yet'],
  'overview.invoiced': ['Фактурирано', 'Invoiced'],
  'overview.invoicedBar': ['Фактурирано', 'Invoiced'],
  'overview.late': ['Задоцнети позиции', 'Late positions'],
  'overview.lateHint': ['Минат планиран крај, не се завршени', 'Past planned end, not finished'],
  'overview.lateItem': ['{code} {name} доцни', '{code} {name} is late'],
  'overview.lateSub': ['Планиран крај {end} · пријавено {pct} %', 'Planned end {end} · reported {pct} %'],
  'overview.location': ['Локација', 'Location'],
  'overview.noGroups': ['Нема групи.', 'No groups.'],
  'overview.noLocation': ['Нема внесена локација', 'No location set'],
  'overview.noLocationHint': ['Залепете ги координатите од Google Maps во Поставки.', 'Paste the coordinates from Google Maps in Settings.'],
  'overview.ofBudget': ['{pct} % од буџетот', '{pct} % of budget'],
  'overview.outstanding': ['Неплатено: {amount}', 'Outstanding: {amount}'],
  'overview.overItem': ['{code} {name} е над буџетот', '{code} {name} is over budget'],
  'overview.overbillWarn': ['Фактурирано е значително повеќе од изведеното. Одобрувајте фактури само за изведена работа.', 'Invoiced is well ahead of work done. Approve invoices only for work that is done.'],
  'overview.paid': ['Платено', 'Paid'],
  'overview.pendingItem': ['{n} фактури чекаат одобрување', '{n} invoices waiting for approval'],
  'overview.pendingSub': ['Буџет и фактури → Фактури', 'Budget & invoices → Invoices'],
  'overview.positions': ['{n} позиции', '{n} positions'],
  'overview.progress': ['Изведено', 'Work done'],
  'overview.progressHint': ['Пондерирано по буџет', 'Weighted by budget'],
  'overview.timeElapsed': ['Изминато време', 'Time elapsed'],
  'overview.tone.red': ['Доцни', 'Late'],
  'overview.tone.amber': ['Внимание', 'Watch'],
  'overview.tone.blue': ['Акција', 'Action'],
  'overview.tone.slate': ['Инфо', 'Info'],
  'overview.undatedItem': ['{n} позиции немаат датуми', '{n} positions have no dates'],
  'overview.undatedSub': ['Без датуми не влегуваат во распоредот', 'Without dates they are not scheduled'],
  'overview.workDone': ['Изведено', 'Work done'],

  // schedule / gantt
  'gantt.actions': ['Дејства', 'Actions'],
  'gantt.active': ['Во тек', 'In progress'],
  'gantt.actual': ['Реализирано', 'Actual'],
  'gantt.addSibling': ['Додај позиција во истата група', 'Add position in the same group'],
  'gantt.addSub': ['Додај подпозиција', 'Add sub-position'],
  'gantt.addTopLevel': ['Додај група / позиција', 'Add group / position'],
  'gantt.all': ['Сите', 'All'],
  'gantt.baseline': ['Основна линија', 'Baseline'],
  'gantt.calendarNote': ['работни денови пон–саб', 'working days Mon–Sat'],
  'gantt.colBudget': ['Буџет', 'Budget'],
  'gantt.colDuration': ['Трае.', 'Dur.'],
  'gantt.colPosition': ['Позиција', 'Position'],
  'gantt.colVendor': ['Изведувач', 'Vendor'],
  'gantt.collapse': ['Собери', 'Collapse'],
  'gantt.comfortable': ['Удобно', 'Comfortable'],
  'gantt.compact': ['Компактно', 'Compact'],
  'gantt.day': ['Ден', 'Day'],
  'gantt.daysShort': ['д', 'd'],
  'gantt.delete': ['Избриши…', 'Delete…'],
  'gantt.deleteNoChildren': ['Позицијата нема подпозиции.', 'This position has no sub-positions.'],
  'gantt.deleteNote': ['Фактурите и документите остануваат зачувани. Бришењето може да се врати.', 'Invoices and documents are kept. The deletion can be undone.'],
  'gantt.deleteTitle': ['Избриши {name}?', 'Delete {name}?'],
  'gantt.deleteWithChildren': ['Ќе се избришат и сите {n} подпозиции.', 'All {n} sub-positions will be deleted too.'],
  'gantt.deleted': ['{name} е избришана.', '{name} deleted.'],
  'gantt.density': ['Густина', 'Density'],
  'gantt.dependencies': ['Зависности', 'Dependencies'],
  'gantt.duplicate': ['Дуплирај', 'Duplicate'],
  'gantt.duplicated': ['Позицијата е дуплирана.', 'Position duplicated.'],
  'gantt.edit': ['Уреди', 'Edit'],
  'gantt.empty': ['Сè уште нема позиции', 'No positions yet'],
  'gantt.emptyHint': ['Додадете ја првата група или позиција, или увезете од Excel.', 'Add the first group or position, or import from Excel.'],
  'gantt.expand': ['Прошири', 'Expand'],
  'gantt.filter': ['Филтер', 'Filter'],
  'gantt.issuesTitle': ['Проблеми на проектот', 'Issues on this project'],
  'gantt.late': ['Задоцнети', 'Late'],
  'gantt.lateBadge': ['доцни', 'late'],
  'gantt.lateF': ['Задоцнети', 'Late'],
  'gantt.legendBaseline': ['Основна линија (план)', 'Baseline (plan)'],
  'gantt.legendDone': ['Завршено', 'Done'],
  'gantt.legendFill': ['Полното во лентата = пријавен напредок', 'Filled part of a bar = reported progress'],
  'gantt.legendLate': ['Доцни / над буџет', 'Late / over budget'],
  'gantt.legendOnTrack': ['Во рок', 'On track'],
  'gantt.legendSunday': ['Недела (неработен ден)', 'Sunday (non-working)'],
  'gantt.legendWatch': ['Внимание / чека потврда', 'Watch / awaiting sign-off'],
  'gantt.level': ['Ниво', 'Level'],
  'gantt.level1': ['Групи', 'Groups'],
  'gantt.level2': ['Позиции', 'Positions'],
  'gantt.level3': ['Сè', 'All'],
  'gantt.month': ['Месец', 'Month'],
  'gantt.newPosition': ['Нова позиција', 'New position'],
  'gantt.noDates': ['Без датуми', 'No dates'],
  'gantt.nothingMatches': ['Нема позиции за овој филтер', 'No positions match this filter'],
  'gantt.ongoing': ['во тек', 'ongoing'],
  'gantt.planned': ['План', 'Planned'],
  'gantt.plannedEnd': ['Планиран крај', 'Planned end'],
  'gantt.positionsCount': ['{n} позиции', '{n} positions'],
  'gantt.print': ['Печати / PDF', 'Print / PDF'],
  'gantt.progress': ['Изведено', 'Done'],
  'gantt.realization': ['Реализација и документи', 'Progress & documents'],
  'gantt.restored': ['Вратено.', 'Restored.'],
  'gantt.search': ['Барај код, позиција, изведувач', 'Search code, position, vendor'],
  'gantt.setDates': ['внеси датуми', 'set dates'],
  'gantt.statusDate': ['Статус на', 'Status date'],
  'gantt.undated': ['Без датуми', 'Undated'],
  'gantt.undatedF': ['Без датуми', 'Undated'],
  'gantt.week': ['Недела', 'Week'],
  'gantt.zoom': ['Размер', 'Zoom'],

  // position editor
  'editor.code': ['Код', 'Code'],
  'editor.created': ['Позицијата е додадена.', 'Position added.'],
  'editor.depTypesSoon': ['Типовите SS / FF / SF и задршка доаѓаат со критичната патека (Фаза А).', 'SS / FF / SF types and lag arrive with the critical path (Phase A).'],
  'editor.dependencies': ['Зависности (претходници)', 'Dependencies (predecessors)'],
  'editor.editSubtitle': ['Уреди позиција', 'Edit position'],
  'editor.end': ['Крај', 'End'],
  'editor.errEnd': ['Крајот е пред почетокот.', 'End is before start.'],
  'editor.errName': ['Внесете назив.', 'Enter a name.'],
  'editor.fs': ['Крај → почеток', 'Finish → start'],
  'editor.milestone': ['Пресвртница (еднодневен настан, се прикажува како ромб)', 'Milestone (one-day event, shown as a diamond)'],
  'editor.name': ['Назив', 'Name'],
  'editor.newSubtitle': ['Нова позиција', 'New position'],
  'editor.newTitle': ['Нова позиција', 'New position'],
  'editor.newUnder': ['Нова подпозиција под {name}', 'New sub-position under {name}'],
  'editor.newVendor': ['Нов изведувач…', 'New vendor…'],
  'editor.noDependencies': ['Нема зависности.', 'No dependencies.'],
  'editor.noParent': ['— Највисоко ниво (група) —', '— Top level (group) —'],
  'editor.notes': ['Белешки', 'Notes'],
  'editor.ownBudget': ['Буџет на позицијата (со ДДВ)', 'Position budget (incl. VAT)'],
  'editor.ownBudgetHint': ['Се форматира додека пишувате: 1435000 → 1.435.000', 'Formats as you type: 1435000 → 1.435.000'],
  'editor.ownBudgetHintParent': ['Само сопствениот износ. Со подпозициите вкупно: {total}', 'Own amount only. Including sub-positions: {total}'],
  'editor.parent': ['Надредена позиција', 'Parent'],
  'editor.pickDependency': ['Изберете претходна позиција…', 'Pick a preceding position…'],
  'editor.saved': ['Зачувано.', 'Saved.'],
  'editor.start': ['Почеток', 'Start'],
  'editor.vendor': ['Изведувач', 'Vendor'],
  'editor.vendorName': ['Назив на изведувач', 'Vendor name'],
  'editor.workDays': ['Работни дена', 'Working days'],

  // realization panel
  'detail.actualEnd': ['Реален крај', 'Actual end'],
  'detail.actualStart': ['Реален почеток', 'Actual start'],
  'detail.approve': ['Одобри и потврди', 'Approve & verify'],
  'detail.brokenFile': ['Датотеката нема линк — прикачете ја повторно', 'This file has no working link — re-upload it'],
  'detail.budget': ['Буџет', 'Budget'],
  'detail.chooseFile': ['Изберете датотека.', 'Choose a file first.'],
  'detail.confirmedBy': ['Потврдил', 'Confirmed by'],
  'detail.docTitle': ['Наслов (опционално)', 'Title (optional)'],
  'detail.documents': ['Документи', 'Documents'],
  'detail.history': ['Историја', 'History'],
  'detail.invoiced': ['Фактурирано', 'Invoiced'],
  'detail.issueTitle': ['Опис на проблемот', 'Issue title'],
  'detail.issues': ['Проблеми', 'Issues'],
  'detail.logIssue': ['Евидентирај проблем', 'Log issue'],
  'detail.money': ['Буџет и фактури', 'Budget & invoices'],
  'detail.noDocuments': ['Нема документи.', 'No documents yet.'],
  'detail.noInvoices': ['Нема фактури за оваа позиција.', 'No invoices on this position.'],
  'detail.noIssues': ['Нема евидентирани проблеми.', 'No issues logged.'],
  'detail.overBudget': ['Фактурирано е {amount} над буџетот.', 'Invoiced is {amount} over budget.'],
  'detail.paid': ['Платено', 'Paid'],
  'detail.pendingVerification': ['Чека потврда', 'Pending verification'],
  'detail.progress': ['Напредок %', 'Progress %'],
  'detail.progressFromTodos': ['Се пресметува од задачите ({done}/{total})', 'Driven by to-dos ({done}/{total})'],
  'detail.realization': ['Реализација', 'Progress'],
  'detail.reasonRequired': ['Внесете причина пред враќање.', 'Add a reason before sending it back.'],
  'detail.saveRealization': ['Зачувај реализација', 'Save progress'],
  'detail.sendBack': ['Врати на доработка', 'Send back'],
  'detail.status': ['Статус', 'Status'],
  'detail.subtitle': ['Реализација', 'Progress'],
  'detail.todos': ['Задачи', 'To-dos'],
  'detail.upload': ['Прикачи', 'Upload'],
  'detail.verification': ['Потврда на изведено', 'Sign-off'],
  'detail.verified': ['Потврдено', 'Verified'],
  'detail.verifyHint': ['Означено како завршено, но никој не го потврдил.', 'Marked completed, but nobody has confirmed it yet.'],
  'detail.verifyNotes': ['Белешка (задолжителна при враќање)', 'Notes (required when sending back)'],
  'status.not_started': ['Не е започната', 'Not started'],
  'status.in_progress': ['Во тек', 'In progress'],
  'status.delayed': ['Одложена', 'Delayed'],
  'status.blocked': ['Блокирана', 'Blocked'],
  'status.completed': ['Завршена', 'Completed'],
  'doc.invoice': ['Фактура', 'Invoice'],
  'doc.contract': ['Договор', 'Contract'],
  'doc.permit': ['Дозвола', 'Permit'],
  'doc.insurance': ['Осигурување', 'Insurance'],
  'doc.drawing': ['Цртеж / план', 'Drawing / plan'],
  'doc.other': ['Друго', 'Other'],
  'history.title': ['Историја на промени', 'Change history'],
  'history.empty': ['Нема евидентирани промени.', 'No changes recorded yet.'],
  'history.created': ['Креирано', 'Created'],
  'history.updated': ['Изменето', 'Updated'],
  'history.deleted': ['Избришано', 'Deleted'],
  'field.name': ['Назив', 'Name'],
  'field.wbs_code': ['Код', 'Code'],
  'field.parent_id': ['Надредена', 'Parent'],
  'field.vendor_id': ['Изведувач', 'Vendor'],
  'field.estimated_start': ['План почеток', 'Planned start'],
  'field.estimated_end': ['План крај', 'Planned end'],
  'field.estimated_cost': ['Буџет', 'Budget'],
  'field.status': ['Статус', 'Status'],
  'field.progress_pct': ['Напредок %', 'Progress %'],
  'field.actual_start': ['Реален почеток', 'Actual start'],
  'field.actual_end': ['Реален крај', 'Actual end'],
  'field.actual_cost': ['Реален трошок', 'Actual cost'],
  'field.notes': ['Белешки', 'Notes'],
  'field.sub_positions': ['Подпозиции', 'Sub-positions'],
  'field.restored': ['Вратено', 'Restored'],
  'field.source': ['Извор', 'Source'],
  'field.duplicated_from': ['Дуплирано од', 'Duplicated from'],
  'field.structure': ['Структура', 'Structure'],

  // issues
  'issue.actual': ['Реално', 'Actual'],
  'issue.actualCost': ['Реален трошок', 'Actual cost impact'],
  'issue.confirmResolved': ['Потврди решено', 'Confirm resolved'],
  'issue.createFix': ['Креирај позиција за поправка во распоредот', 'Create a fix position on the schedule'],
  'issue.createTask': ['Креирај позиција', 'Create position'],
  'issue.discovered': ['Откриено', 'Discovered'],
  'issue.estCost': ['Проценет трошок', 'Est. cost impact'],
  'issue.estDelay': ['Проценето доцнење (дена)', 'Est. delay (days)'],
  'issue.fixTask': ['Поправка', 'Fix task'],
  'issue.howResolved': ['Како е решено?', 'How was it resolved?'],
  'issue.impact': ['Проценето влијание', 'Est. impact'],
  'issue.markResolved': ['Означи решено', 'Mark resolved'],
  'issue.start': ['Започни решавање', 'Start resolving'],
  'issue.sev.low': ['Ниско', 'Low'],
  'issue.sev.medium': ['Средно', 'Medium'],
  'issue.sev.high': ['Високо', 'High'],
  'issue.sev.critical': ['Критично', 'Critical'],
  'issue.status.open': ['Отворено', 'Open'],
  'issue.status.in_progress': ['Во решавање', 'In progress'],
  'issue.status.resolved': ['Решено', 'Resolved'],

  // budget & invoices
  'budget.amount': ['Износ', 'Amount'],
  'budget.approve': ['Одобри', 'Approve'],
  'budget.approved': ['Фактурата е одобрена.', 'Invoice approved.'],
  'budget.check': ['провери', 'check'],
  'budget.currency': ['Валута', 'Currency'],
  'budget.date': ['Датум', 'Date'],
  'budget.deleteInvoice': ['Избриши ја фактурата?', 'Delete this invoice?'],
  'budget.description': ['Опис', 'Description'],
  'budget.difference': ['Разлика', 'Difference'],
  'budget.done': ['Изведено', 'Done'],
  'budget.dueDate': ['Рок за плаќање', 'Due date'],
  'budget.editInvoice': ['Уреди фактура', 'Edit invoice'],
  'budget.errAmount': ['Внесете износ.', 'Enter an amount.'],
  'budget.errDate': ['Внесете датум.', 'Enter a date.'],
  'budget.invoice': ['Фактура', 'Invoice'],
  'budget.invoiceAdded': ['Фактурата е додадена.', 'Invoice added.'],
  'budget.invoices': ['Фактури', 'Invoices'],
  'budget.net': ['Основица', 'Net'],
  'budget.newInvoice': ['Нова фактура', 'New invoice'],
  'budget.newInvoiceFor': ['Нова фактура за оваа позиција', 'New invoice for this position'],
  'budget.noInvoices': ['Нема фактури', 'No invoices'],
  'budget.noPositions': ['Нема позиции', 'No positions'],
  'budget.number': ['Број на фактура', 'Invoice no.'],
  'budget.okBudget': ['Во рамки на буџетот: {after} од {budget}.', 'Within budget: {after} of {budget}.'],
  'budget.outstanding': ['Неплатено', 'Outstanding'],
  'budget.paidOn': ['Платено на', 'Paid on'],
  'budget.payment': ['Плаќање', 'Payment'],
  'budget.pdf': ['PDF на фактурата', 'Invoice PDF'],
  'budget.pdfReplace': ['Прикачете нов за да го замените постоечкиот.', 'Upload a new file to replace the current one.'],
  'budget.position': ['Позиција', 'Position'],
  'budget.positions': ['Позиции', 'Positions'],
  'budget.recordPayment': ['Евидентирај плаќање', 'Record payment'],
  'budget.searchInvoices': ['Барај изведувач, број, позиција', 'Search vendor, number, position'],
  'budget.status': ['Статус', 'Status'],
  'budget.subtitle': ['Сите износи се со ДДВ, во EUR. Фактура: примена → одобрена → платена.', 'All amounts incl. VAT, in EUR. Invoice: received → approved → paid.'],
  'budget.total': ['Вкупно', 'Total'],
  'budget.totalWithVat': ['Вкупно со ДДВ', 'Total incl. VAT'],
  'budget.vat': ['ДДВ', 'VAT'],
  'budget.vatAmount': ['Износ на ДДВ', 'VAT amount'],
  'budget.view': ['Приказ', 'View'],
  'budget.warnAheadOfWork': ['Пријавено изведено е {pct} % (≈ {earned}). Фактурата е пред изведената работа — одобрете ја откако ќе се изведе.', 'Reported progress is {pct} % (≈ {earned}). This invoice is ahead of the work — approve it once the work is done.'],
  'budget.warnOverBudget': ['Со оваа фактура позицијата оди на {after}, над буџетот од {budget}.', 'With this invoice the position reaches {after}, over its {budget} budget.'],
  'pay.received': ['Примена', 'Received'],
  'pay.approved': ['Одобрена', 'Approved'],
  'pay.partial': ['Делумно платена', 'Partly paid'],
  'pay.paid': ['Платена', 'Paid'],
  'pay.rejected': ['Одбиена', 'Rejected'],

  // analytics
  'analytics.actualSoFar': ['Реален трошок досега', 'Actual cost so far'],
  'analytics.breakeven': ['Достигната точка на рентабилност', 'Break-even reached'],
  'analytics.c.cumNet': ['Кумулативно нето', 'Cumulative net'],
  'analytics.c.estRev': ['Проценет приход', 'Est. revenue'],
  'analytics.c.period': ['Период', 'Period'],
  'analytics.cumulative': ['Кумулативно фактурирано', 'Cumulative invoiced'],
  'analytics.estLogged': ['Проценет трошок (евидентиран)', 'Est. cost (logged)'],
  'analytics.g.week': ['Недела', 'Week'],
  'analytics.g.month': ['Месец', 'Month'],
  'analytics.g.quarter': ['Квартал', 'Quarter'],
  'analytics.g.year': ['Година', 'Year'],
  'analytics.granularity': ['Период', 'Period'],
  'analytics.l.actCost': ['Реален трошок', 'Actual cost'],
  'analytics.l.actCumCost': ['Реален кумулативен трошок', 'Actual cumulative cost'],
  'analytics.l.actCumRev': ['Реален кумулативен приход', 'Actual cumulative revenue'],
  'analytics.l.actRev': ['Реален приход', 'Actual revenue'],
  'analytics.l.estCost': ['Проценет трошок', 'Est. cost'],
  'analytics.l.estCumCost': ['Проценет кумулативен трошок', 'Est. cumulative cost'],
  'analytics.l.estCumRev': ['Проценет кумулативен приход', 'Est. cumulative revenue'],
  'analytics.net': ['Нето позиција', 'Net position'],
  'analytics.noData': ['Сè уште нема податоци.', 'No data yet.'],
  'analytics.perPeriod': ['Фактурирано по период', 'Invoiced per period'],
  'analytics.preBreakeven': ['Пред рентабилност', 'Pre break-even'],
  'analytics.projectedCost': ['Планиран трошок', 'Projected cost'],
  'analytics.projectedCostHint': ['Збир на буџетите на сите позиции', 'Sum of all position budgets'],
  'analytics.projectedProfit': ['Планирана добивка', 'Projected profit'],
  'analytics.projectedProfitHint': ['Планиран приход − планиран трошок', 'Projected revenue − projected cost'],
  'analytics.projectedRevenue': ['Планиран приход', 'Projected revenue'],
  'analytics.projectedRevenueHint': ['Од продажбата на станови (CRM)', 'From unit sales (CRM)'],
  'analytics.projectedVsReal': ['Планирано наспроти реално', 'Projected vs. real'],
  'analytics.realCost': ['Реален трошок', 'Real cost'],
  'analytics.realCostHint': ['Збир на фактурите', 'Sum of invoices'],
  'analytics.realProfit': ['Реална добивка (досега)', 'Real profit (so far)'],
  'analytics.realProfitHint': ['Реален приход − реален трошок', 'Real revenue − real cost'],
  'analytics.realRevenue': ['Реален приход', 'Real revenue'],
  'analytics.realRevenueHint': ['Наплатени уплати', 'Payments collected'],
  'analytics.status': ['Статус', 'Status'],
  'analytics.subtitle': ['Само за читање. Фактурите се внесуваат во Буџет и фактури.', 'Read-only. Invoices are entered in Budget & invoices.'],
  'analytics.remaining': ['Преостанато до буџетот', 'Remaining to budget'],
  'analytics.remainingHint': ['Буџет − фактурирано', 'Budget − invoiced'],
  'analytics.invoicedPct': ['Искористен буџет', 'Budget used'],
  'analytics.invoicedPctHint': ['Фактурирано / буџет', 'Invoiced / budget'],
  'analytics.c.invoiced': ['Фактурирано во периодот', 'Invoiced in period'],
  'analytics.c.cumInvoiced': ['Кумулативно фактурирано', 'Cumulative invoiced'],
  'analytics.table': ['По периоди', 'By period'],

  // notifications
  'bell.awaitingSignoff': ['чека потврда', 'awaiting sign-off'],
  'bell.billOverdue': ['фактурата доцни', 'bill overdue'],
  'bell.due': ['рок', 'due'],
  'bell.empty': ['Ништо итно.', 'Nothing urgent right now.'],
  'bell.openIssue': ['отворен проблем', 'open issue'],
  'bell.paymentOverdue': ['уплатата доцни', 'payment overdue'],
  'bell.soon': ['почнува/завршува наскоро', 'starting/ending soon'],
  'bell.title': ['Бара внимание', 'Needs attention'],
  'bell.tone.red': ['доцни', 'overdue'],
  'bell.tone.amber': ['внимание', 'watch'],
  'bell.tone.blue': ['позиција', 'position'],

  // new project
  'newProject.address': ['Адреса', 'Address'],
  'newProject.basics': ['Основни податоци', 'Basics'],
  'newProject.budget': ['Вкупен буџет (со ДДВ)', 'Total budget (incl. VAT)'],
  'newProject.budgetHint': ['Може да остане празно — се пресметува од позициите.', 'Can stay empty — it is computed from the positions.'],
  'newProject.continueImport': ['Продолжи кон увоз', 'Continue to import'],
  'newProject.coords': ['Координати', 'Coordinates'],
  'newProject.coordsHint': ['Десен клик на Google Maps → копирај → залепи тука. Или кликнете на мапата.', 'Right-click on Google Maps → copy → paste here. Or click the map.'],
  'newProject.coordsInvalid': ['Формат: 41.350496, 21.564121', 'Format: 41.350496, 21.564121'],
  'newProject.copyFrom': ['Копирај од', 'Copy from'],
  'newProject.create': ['Креирај проект', 'Create project'],
  'newProject.created': ['Проектот „{name}“ е креиран.', 'Project “{name}” created.'],
  'newProject.end': ['Планиран крај', 'Planned end'],
  'newProject.errCopy': ['Изберете проект.', 'Choose a project.'],
  'newProject.errName': ['Внесете назив.', 'Enter a name.'],
  'newProject.investor': ['Инвеститор', 'Investor'],
  'newProject.location': ['Локација', 'Location'],
  'newProject.name': ['Назив на проектот', 'Project name'],
  'newProject.start': ['Почеток', 'Start'],
  'newProject.structure': ['Структура на позициите', 'Position structure'],
  'newProject.structureHint': ['Сè може да се менува и по креирањето.', 'Everything can be changed after creating.'],
  'newProject.subtitle': ['Внесете го проектот директно во апликацијата. Увозот од Excel е само една од можностите.', 'Set the project up directly in the app. Excel import is just one option.'],
  'newProject.type': ['Тип на објект', 'Building type'],
  'newProject.typeResidential': ['Станбена зграда', 'Residential building'],
  'newProject.typeCommercial': ['Деловен објект', 'Commercial building'],
  'newProject.typeHouse': ['Куќа', 'House'],
  'newProject.typeInfrastructure': ['Инфраструктура', 'Infrastructure'],
  'newProject.typeOther': ['Друго', 'Other'],
  'newProject.s.empty': ['Празен проект', 'Empty project'],
  'newProject.s.emptyHint': ['Почнете од нула и додадете позиции рачно.', 'Start from scratch and add positions yourself.'],
  'newProject.s.template': ['Шаблон: станбена зграда', 'Template: residential building'],
  'newProject.s.templateHint': ['Групи А / Б / Ц со 44 типични позиции, без датуми и износи.', 'Groups А / Б / Ц with 44 typical positions, no dates or amounts.'],
  'newProject.s.copy': ['Копирај постоечки проект', 'Copy an existing project'],
  'newProject.s.copyHint': ['Позиции, изведувачи и зависности, без реализација и фактури.', 'Positions, vendors and dependencies — no actuals or invoices.'],
  'newProject.s.excel': ['Увоз од Excel', 'Import from Excel'],
  'newProject.s.excelHint': ['Гантограм + фактури во вашиот формат.', 'Gantt workbook + invoices in your format.'],

  // settings
  'settings.budgetHint': ['Информативно. Буџетот во извештаите е збир од позициите.', 'For reference. Reports use the sum of the positions.'],
  'settings.contact': ['Контакт', 'Contact'],
  'settings.danger': ['Бришење на проект', 'Delete project'],
  'settings.dangerHint': ['Ги брише сите позиции, фактури и документи на проектот.', 'Removes all positions, invoices and documents of this project.'],
  'settings.deleteMsg': ['Ова не може да се врати.', 'This cannot be undone.'],
  'settings.deleteProject': ['Избриши проект', 'Delete project'],
  'settings.deleteTitle': ['Избриши го „{name}“?', 'Delete “{name}”?'],
  'settings.noVendors': ['Нема изведувачи', 'No vendors'],
  'settings.phone': ['Телефон', 'Phone'],
  'settings.status': ['Статус', 'Status'],
  'settings.subtitle': ['Податоци за проектот, локација и изведувачи.', 'Project details, location and vendors.'],
  'settings.trade': ['Дејност', 'Trade'],
  'settings.vendors': ['Изведувачи и добавувачи', 'Vendors & suppliers'],
  'settings.vendorsHint': ['Заеднички за сите проекти — истиот изведувач може да работи на повеќе градилишта.', 'Shared across projects — the same vendor can work on several sites.'],

  // import
  'import.action': ['Дејство', 'Action'],
  'import.check': ['Провери датотеки', 'Check files'],
  'import.choose': ['Изберете датотеки', 'Choose files'],
  'import.commit': ['Увези {n} позиции и {i} фактури', 'Import {n} positions and {i} invoices'],
  'import.commitNote': ['Ништо не е запишано до овој чекор.', 'Nothing is written until this step.'],
  'import.done': ['„{name}“ е увезен.', '“{name}” imported.'],
  'import.dropHint': ['Excel гантограм (.xlsx) и, по избор, PDF фактурите (ф-ра А01.pdf …).', 'Excel Gantt workbook (.xlsx) and, optionally, the invoice PDFs (ф-ра А01.pdf …).'],
  'import.dropTitle': ['Довлечете ги датотеките тука', 'Drop the files here'],
  'import.formatNote': ['Формат: лист со колони ID / активност / Почеток / Крај / Реализирано / Проектирана цена (два реда по позиција: план и реализација) и лист „Фактури“. PDF фактурите се поврзуваат по кодот во името.', 'Format: a sheet with ID / activity / Start / End / Realised / Planned price (two rows per position: plan and actual) and a “Фактури” sheet. Invoice PDFs are matched by the code in the file name.'],
  'import.importing': ['Се увезува…', 'Importing…'],
  'import.newProject': ['Нов проект', 'New project'],
  'import.noProblems': ['Не се најдени проблеми.', 'No problems found.'],
  'import.pdfCount': ['{n} PDF фактури', '{n} invoice PDFs'],
  'import.problem': ['Проблем', 'Problem'],
  'import.problemCounts': ['{e} грешки · {w} предупредувања · {q} прашања', '{e} errors · {w} warnings · {q} questions'],
  'import.problems': ['Пронајдени проблеми', 'Problems found'],
  'import.reading': ['Се читаат датотеките…', 'Reading files…'],
  'import.severity': ['Важност', 'Severity'],
  'import.sev.error': ['Грешка', 'Error'],
  'import.sev.warning': ['Предупредување', 'Warning'],
  'import.sev.question': ['Прашање', 'Question'],
  'import.step1': ['Датотеки', 'Files'],
  'import.step2': ['Проверка', 'Review'],
  'import.step3': ['Увоз', 'Import'],
  'import.subtitle': ['Самостојна алатка: нов проект или ажурирање на постоечки. Ништо не се запишува пред да потврдите.', 'Stand-alone tool: a new project or an update to an existing one. Nothing is written until you confirm.'],
  'import.sumBudget': ['вкупен буџет', 'total budget'],
  'import.sumGroups': ['групи', 'groups'],
  'import.sumInvoices': ['фактури ({n} PDF)', 'invoices ({n} PDFs)'],
  'import.sumPositions': ['позиции, од кои {n} подпозиции', 'positions, {n} of them sub-positions'],
  'import.sumVendors': ['изведувачи', 'vendors'],
  'import.target.new': ['Нов проект', 'New project'],
  'import.target.newHint': ['Се креира проект со сите позиции и фактури.', 'Creates a project with all positions and invoices.'],
  'import.target.existing': ['Ажурирај постоечки проект', 'Update an existing project'],
  'import.target.existingHint': ['Позициите се спојуваат по код (А01, Б02 …); фактурите се додаваат.', 'Positions are matched by code (А01, Б02 …); invoices are added.'],
  'import.where': ['Каде', 'Where'],
  'import.whereTo': ['Каде да се увезе?', 'Import into'],
  'import.msg.end_before_start': ['Крајот ({end}) е пред почетокот ({start}).', 'End ({end}) is before start ({start}).'],
  'import.msg.parent_missing': ['Надредената {parent} не е пронајдена; се увезува под групата.', 'Parent {parent} not found; imported under its group.'],
  'import.msg.undated': ['{n} позиции немаат датуми.', '{n} positions have no dates.'],
  'import.msg.pdf_unreadable': ['PDF {file} нема читлив износ или датум.', 'PDF {file} has no readable amount or date.'],
  'import.msg.dates_differ': ['Кај {n} фактури датумот во листот се разликува од датумот на PDF.', '{n} sheet dates differ from the date on the PDF.'],
  'import.msg.amount_differs': ['Износот во листот се разликува од PDF.', 'Amount in the sheet differs from the PDF.'],
  'import.msg.orphan_invoice': ['Фактура за позиција што не постои во гантограмот.', 'Invoice for a position that is not in the Gantt sheet.'],
  'import.msg.desc_mismatch': ['Текстот на фактурата „{text}“ не одговара на „{name}“.', 'Invoice text “{text}” doesn’t look like “{name}”.'],
  'import.msg.no_progress': ['{n} фактури се за позиции без пријавен напредок.', '{n} invoices are for positions with no reported progress.'],
  'import.msg.vendor_dupe': ['„{names}“ изгледаат како ист изведувач.', '“{names}” look like the same vendor.'],
  'import.opt.fix': ['Поправи: крај = почеток', 'Fix: end = start'],
  'import.opt.clear': ['Увези без датуми', 'Import without dates'],
  'import.opt.keep': ['Увези како што е', 'Import as is'],
  'import.opt.skip': ['Прескокни', 'Skip'],
  'import.opt.pdf': ['Користи податок од PDF', 'Use the PDF value'],
  'import.opt.sheet': ['Користи податок од листот', 'Use the sheet value'],
  'import.opt.flag': ['Увези, означи за проверка', 'Import, mark for review'],
  'import.opt.received': ['Увези како „Примена“ (неодобрена)', 'Import as “Received” (not approved)'],
  'import.opt.merge': ['Спои во еден изведувач', 'Merge into one vendor'],
  // Phase A — scheduling
  'gantt.baselineLatest': ['последна', 'latest'],
  'gantt.baselineName': ['Основен план', 'Baseline'],
  'gantt.baselinePick': ['Спореди со', 'Compare with'],
  'gantt.baselinePlan': ['Планирани датуми', 'Planned dates'],
  'gantt.baselineSaved': ['Основниот план е зачуван', 'Baseline saved'],
  'gantt.colFloat': ['Резерва', 'Float'],
  'gantt.constraintBadge': ['ограничување', 'constraint'],
  'gantt.criticalCount': ['Критични', 'Critical'],
  'gantt.criticalF': ['Критична патека', 'Critical path'],
  'gantt.floatHint': ['Работни денови што позицијата може да доцни без да го помести крајот на проектот', 'Working days a position can slip without moving the project finish'],
  'gantt.floatTitle': ['Вкупна резерва {tf} д · слободна {ff} д', 'Total float {tf} d · free float {ff} d'],
  'gantt.forecast': ['Прогноза', 'Forecast'],
  'gantt.forecastEnd': ['Прогнозиран крај', 'Forecast finish'],
  'gantt.legendCritical': ['Критично', 'Critical'],
  'gantt.loopError': ['Врските прават круг: {path}. Отстранете една врска за да се пресмета распоредот.', 'The links form a loop: {path}. Remove one link to calculate the schedule.'],
  'gantt.newDates': ['Нови датуми', 'New dates'],
  'gantt.onPlan': ['според план', 'on plan'],
  'gantt.reschedule': ['Пресметај распоред', 'Reschedule'],
  'gantt.rescheduleApply': ['Примени ({n})', 'Apply ({n})'],
  'gantt.rescheduleHint': ['Позициите што не се започнати се поместуваат според врските, календарот и денешниот ден. Започнатите и завршените не се менуваат.', 'Positions not yet started move according to links, the calendar and today. Started and finished positions stay as they are.'],
  'gantt.rescheduleNone': ['Сите планирани датуми се веќе усогласени.', 'All planned dates are already consistent.'],
  'gantt.rescheduleTitle': ['Пресметај нов распоред', 'Reschedule'],
  'gantt.rescheduled': ['Распоредот е ажуриран', 'Schedule updated'],
  'gantt.saveBaseline': ['Зачувај основен план', 'Save baseline'],
  'gantt.saveBaselineHint': ['Снимка од денешните датуми и буџет за споредба подоцна', "Snapshot of today's dates and budget to compare against later"],
  'gantt.wdShort': ['р.д.', 'wd'],
  'fly.noTerrain': ['3D-теренот од Cesium ion не е достапен (проверете го токенот / Allowed URLs) — прикажан е рамен сателитски приказ.', '3D terrain from Cesium ion is not available (check the token / Allowed URLs) — showing a flat satellite view.'],
  'fly.failed': ['3D-приказот не може да се вчита.', 'The 3D view could not start.'],
  'gantt.deadline': ['рок', 'deadline'],
  'editor.depHelp': ['КС = почеток по крај · ПП = почеток со почеток · КК = крај со крај · ПК = крај по почеток. Доцнење во работни денови (може и негативно).', 'FS = start after finish · SS = start with start · FF = finish with finish · SF = finish after start. Lag in working days (may be negative).'],
  'editor.depLag': ['Доцнење (р.д.)', 'Lag (wd)'],
  'editor.depPredecessor': ['Претходна позиција', 'Predecessor'],
  'editor.depType': ['Врска', 'Link'],
  'editor.depTypeFS': ['Почнува откако претходната ќе заврши', 'Starts after the predecessor finishes'],
  'editor.depTypeSS': ['Почнува кога почнува претходната', 'Starts when the predecessor starts'],
  'editor.depTypeFF': ['Завршува кога завршува претходната', 'Finishes when the predecessor finishes'],
  'editor.depTypeSF': ['Завршува откако претходната ќе почне', 'Finishes after the predecessor starts'],
  'editor.depShortFS': ['крај→почеток', 'finish→start'],
  'editor.depShortSS': ['почеток→почеток', 'start→start'],
  'editor.depShortFF': ['крај→крај', 'finish→finish'],
  'editor.depShortSF': ['почеток→крај', 'start→finish'],
  'editor.calendar': ['Календар', 'Calendar'],
  'editor.calendarProject': ['Работен календар на проектот', 'Project working calendar'],
  'editor.calendarSeven': ['7 дена (календарски)', '7-day (calendar days)'],
  'editor.calendarSevenHint': ['За сушење, стврднување на бетон и сл. — се бројат и неделите и празниците.', 'For curing, drying etc. — Sundays and holidays count.'],
  'editor.constraint': ['Ограничување', 'Constraint'],
  'editor.constraintDate': ['Датум на ограничување', 'Constraint date'],
  'editor.constraintNone': ['Што порано', 'As soon as possible'],
  'editor.constraintSnet': ['Почеток не пред', 'Start no earlier than'],
  'editor.constraintFnlt': ['Крај најдоцна до', 'Finish no later than'],
  'editor.constraintMso': ['Мора да почне на', 'Must start on'],
  'detail.schedule': ['Распоред', 'Schedule'],
  'detail.critical': ['Критична', 'Critical'],
  'detail.nearCritical': ['Речиси критична', 'Near-critical'],
  'detail.hasFloat': ['Има резерва', 'Has float'],
  'detail.done': ['Завршена', 'Done'],
  'detail.forecastStart': ['Прогн. почеток', 'Forecast start'],
  'detail.forecastEnd': ['Прогн. крај', 'Forecast finish'],
  'detail.latestEnd': ['Најдоцнен крај', 'Latest finish'],
  'detail.float': ['Резерва вк./сл.', 'Float total/free'],
  'detail.slip': ['Доцни {n} работни дена во однос на планот.', '{n} working days behind the plan.'],
  'detail.drivenBy': ['Почетокот го одредува', 'Start driven by'],
  'detail.chain': ['Синџир', 'Chain'],
  'detail.thisOne': ['оваа позиција', 'this position'],
  'detail.why.plan': ['планираниот датум', 'the planned date'],
  'detail.why.status_date': ['денешниот ден (не е започната)', 'today (not started yet)'],
  'detail.why.constraint': ['ограничувањето', 'the constraint'],
  'detail.violation.fnlt': ['Прогнозираниот крај е по датумот „Крај најдоцна до“.', 'Forecast finish is after the “finish no later than” date.'],
  'detail.violation.mso': ['Претходните позиции не дозволуваат почеток на задолжителниот датум.', 'Predecessors prevent starting on the must-start date.'],
  'cal.title': ['Работен календар', 'Working calendar'],
  'cal.hint': ['Се користи за траење, доцнење и критична патека. Државните празници важат за сите проекти.', 'Used for durations, lags and the critical path. National holidays apply to every project.'],
  'cal.weekdays': ['Работни денови', 'Working days'],
  'cal.national': ['Државни празници', 'National holidays'],
  'cal.project': ['Посебни денови за проектот', 'Project exceptions'],
  'cal.projectEmpty': ['Нема посебни денови.', 'No exceptions.'],
  'cal.date': ['Датум', 'Date'],
  'cal.name': ['Опис', 'Description'],
  'cal.working': ['Работен ден', 'Working day'],
  'cal.nonWorking': ['Неработен', 'Non-working'],
  'cal.saved': ['Календарот е зачуван', 'Calendar saved'],
  'cal.day.0': ['Пон', 'Mon'], 'cal.day.1': ['Вто', 'Tue'], 'cal.day.2': ['Сре', 'Wed'], 'cal.day.3': ['Чет', 'Thu'],
  'cal.day.4': ['Пет', 'Fri'], 'cal.day.5': ['Саб', 'Sat'], 'cal.day.6': ['Нед', 'Sun'],
}

export default S
